services:
  test-db:
    image: postgis/postgis:13-master
      # Required when running on platform other than amd64, like Apple M1/M2:
    platform: linux/amd64
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
      PGUSER: "test"
    ports:
      - 5431:5431
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "admin"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 40s

volumes:
  db-data:
